documents/urls.py
# -*- coding: utf-8 -*-
#
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .views import DocumentUploadView, DocumentUpdateView
from . import views

js_info_dict = {
    'packages': ('geonode.documents',),
}

urlpatterns = [  # 'geonode.documents.views',
    url(r'^$',
        TemplateView.as_view(
        template_name='documents/document_list.html'),
        {'facet_type': 'documents'},
        name='document_browse'),
    url(r'^(?P<docid>\d+)/?$',
        views.document_detail, name='document_detail'),
    url(r'^(?P<docid>\d+)/download/?$',
        views.document_download, name='document_download'),
    url(r'^(?P<docid>\d+)/replace$', login_required(DocumentUpdateView.as_view()),
        name="document_replace"),
    url(r'^(?P<docid>\d+)/remove$',
        views.document_remove, name="document_remove"),
    url(r'^upload/?$', login_required(
        DocumentUploadView.as_view()), name='document_upload'),
    url(r'^search/?$', views.document_search_page,
        name='document_search_page'),
    url(r'^(?P<docid>[^/]*)/metadata_detail$', views.document_metadata_detail,
        name='document_metadata_detail'),
    url(r'^(?P<docid>\d+)/metadata$',
        views.document_metadata, name='document_metadata'),
    url(
        r'^metadata/batch/(?P<ids>[^/]*)/$',
        views.document_batch_metadata,
        name='document_batch_metadata'),
    url(r'^(?P<docid>\d+)/metadata_advanced$', views.document_metadata_advanced,
        name='document_metadata_advanced'),
    url(r'^(?P<docid>[^/]*)/thumb_upload$',
        views.document_thumb_upload, name='document_thumb_upload'),
]

documents/models.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import logging
import os
import uuid
from urlparse import urlparse

from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.urlresolvers import reverse
from django.contrib.staticfiles import finders
from django.utils.translation import ugettext_lazy as _

from geonode.layers.models import Layer
from geonode.base.models import ResourceBase, resourcebase_post_save, Link
from geonode.documents.enumerations import DOCUMENT_TYPE_MAP, DOCUMENT_MIMETYPE_MAP
from geonode.maps.signals import map_changed_signal
from geonode.maps.models import Map
from geonode.security.utils import remove_object_permissions

IMGTYPES = ['jpg', 'jpeg', 'tif', 'tiff', 'png', 'gif']

logger = logging.getLogger(__name__)


class Document(ResourceBase):

    """
    A document is any kind of information that can be attached to a map such as pdf, images, videos, xls...
    """

    doc_file = models.FileField(upload_to='documents',
                                null=True,
                                blank=True,
                                max_length=255,
                                verbose_name=_('File'))

    extension = models.CharField(max_length=128, blank=True, null=True)

    doc_type = models.CharField(max_length=128, blank=True, null=True)

    doc_url = models.URLField(
        blank=True,
        null=True,
        max_length=255,
        help_text=_('The URL of the document if it is external.'),
        verbose_name=_('URL'))

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('document_detail', args=(self.id,))

    @property
    def name_long(self):
        if not self.title:
            return str(self.id)
        else:
            return '%s (%s)' % (self.title, self.id)

    def find_placeholder(self):
        placeholder = 'documents/{0}-placeholder.png'
        return finders.find(placeholder.format(self.extension), False) or \
            finders.find(placeholder.format('generic'), False)

    def is_file(self):
        return self.doc_file and self.extension

    def is_image(self):
        return self.is_file() and self.extension.lower() in IMGTYPES

    @property
    def class_name(self):
        return self.__class__.__name__

    class Meta(ResourceBase.Meta):
        pass


class DocumentResourceLink(models.Model):

    # relation to the document model
    document = models.ForeignKey(Document, related_name='links')

    # relation to the resource model
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    resource = GenericForeignKey('content_type', 'object_id')


def get_related_documents(resource):
    if isinstance(resource, Layer) or isinstance(resource, Map):
        content_type = ContentType.objects.get_for_model(resource)
        return Document.objects.filter(links__content_type=content_type,
                                       links__object_id=resource.pk)
    else:
        return None


def get_related_resources(document):
    if document.links:
        return [
            link.content_type.get_object_for_this_type(id=link.object_id)
            for link in document.links.all()
        ]
    else:
        return []


def pre_save_document(instance, sender, **kwargs):
    base_name, extension, doc_type = None, None, None

    if instance.doc_file:
        base_name, extension = os.path.splitext(instance.doc_file.name)
        instance.extension = extension[1:]
        doc_type_map = DOCUMENT_TYPE_MAP
        doc_type_map.update(getattr(settings, 'DOCUMENT_TYPE_MAP', {}))
        if doc_type_map is None:
            doc_type = 'other'
        else:
            doc_type = doc_type_map.get(instance.extension, 'other')
        instance.doc_type = doc_type

    elif instance.doc_url:
        if '.' in urlparse(instance.doc_url).path:
            instance.extension = urlparse(instance.doc_url).path.rsplit('.')[-1]

    if not instance.uuid:
        instance.uuid = str(uuid.uuid1())
    instance.csw_type = 'document'

    if instance.abstract == '' or instance.abstract is None:
        instance.abstract = 'No abstract provided'

    if instance.title == '' or instance.title is None:
        instance.title = instance.doc_file.name

    resources = get_related_resources(instance)

    if resources:
        instance.bbox_x0 = min([r.bbox_x0 for r in resources])
        instance.bbox_x1 = max([r.bbox_x1 for r in resources])
        instance.bbox_y0 = min([r.bbox_y0 for r in resources])
        instance.bbox_y1 = max([r.bbox_y1 for r in resources])
    else:
        instance.bbox_x0 = -180
        instance.bbox_x1 = 180
        instance.bbox_y0 = -90
        instance.bbox_y1 = 90


def post_save_document(instance, *args, **kwargs):

    name = None
    ext = instance.extension
    mime_type_map = DOCUMENT_MIMETYPE_MAP
    mime_type_map.update(getattr(settings, 'DOCUMENT_MIMETYPE_MAP', {}))
    mime = mime_type_map.get(ext, 'text/plain')
    url = None

    if instance.doc_file:
        name = "Hosted Document"
        url = '%s%s' % (
            settings.SITEURL[:-1],
            reverse('document_download', args=(instance.id,)))
    elif instance.doc_url:
        name = "External Document"
        url = instance.doc_url

    if name and url and ext:
        Link.objects.get_or_create(
            resource=instance.resourcebase_ptr,
            url=url,
            defaults=dict(
                extension=ext,
                name=name,
                mime=mime,
                url=url,
                link_type='data',))


def create_thumbnail(sender, instance, created, **kwargs):
    from .tasks import create_document_thumbnail

    create_document_thumbnail.delay(object_id=instance.id)


def update_documents_extent(sender, **kwargs):
    documents = get_related_documents(sender)
    if documents:
        for document in documents:
            document.save()


def pre_delete_document(instance, sender, **kwargs):
    remove_object_permissions(instance.get_self_resource())


signals.pre_save.connect(pre_save_document, sender=Document)
signals.post_save.connect(create_thumbnail, sender=Document)
signals.post_save.connect(post_save_document, sender=Document)
signals.post_save.connect(resourcebase_post_save, sender=Document)
signals.pre_delete.connect(pre_delete_document, sender=Document)
map_changed_signal.connect(update_documents_extent)

documents/forms.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import json
import os
import re
from autocomplete_light.registry import autodiscover

from django import forms
from django.utils.translation import ugettext as _
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.forms import HiddenInput, TextInput
from modeltranslation.forms import TranslationModelForm

from geonode.documents.models import (
    Document,
    DocumentResourceLink,
    get_related_resources,
)
from geonode.maps.models import Map
from geonode.layers.models import Layer

autodiscover() # flake8: noqa

from geonode.base.forms import ResourceBaseForm


class DocumentFormMixin(object):

    def generate_link_choices(self, resources=None):

        if resources is None:
            resources = list(Layer.objects.all())
            resources += list(Map.objects.all())
            resources.sort(key=lambda x: x.title)

        choices = []
        for obj in resources:
            type_id = ContentType.objects.get_for_model(obj.__class__).id
            choices.append([
                "type:%s-id:%s" % (type_id, obj.id),
                '%s (%s)' % (obj.title, obj.polymorphic_ctype.model)
            ])

        return choices

    def generate_link_values(self, resources=None):
        choices = self.generate_link_choices(resources=resources)
        return [choice[0] for choice in choices]

    def save_many2many(self, links_field='links'):
        # create and fetch desired links
        instances = []
        for link in self.cleaned_data[links_field]:
            matches = re.match("type:(\d+)-id:(\d+)", link)
            if matches:
                content_type = ContentType.objects.get(id=matches.group(1))
                instance, _ = DocumentResourceLink.objects.get_or_create(
                    document=self.instance,
                    content_type=content_type,
                    object_id=matches.group(2),
                )
                instances.append(instance)

        # delete remaining links
        DocumentResourceLink.objects\
                .exclude(pk__in=[i.pk for i in instances]).delete()


class DocumentForm(ResourceBaseForm, DocumentFormMixin):

    links = forms.MultipleChoiceField(
        label=_("Link to"),
        required=False)

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['links'].choices = self.generate_link_choices()
        self.fields['links'].initial = self.generate_link_values(
            resources=get_related_resources(self.instance)
        )

    class Meta(ResourceBaseForm.Meta):
        model = Document
        exclude = ResourceBaseForm.Meta.exclude + (
            'content_type',
            'object_id',
            'doc_file',
            'extension',
            'doc_type',
            'doc_url')


class DocumentDescriptionForm(forms.Form):
    title = forms.CharField(300)
    abstract = forms.CharField(2000, widget=forms.Textarea, required=False)
    keywords = forms.CharField(500, required=False)


class DocumentReplaceForm(forms.ModelForm):

    """
    The form used to replace a document.
    """

    class Meta:
        model = Document
        fields = ['doc_file', 'doc_url']

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentReplaceForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(
                _("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(
                doc_file.name)[1].lower()[
                1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file


class DocumentCreateForm(TranslationModelForm, DocumentFormMixin):

    """
    The document upload form.
    """
    permissions = forms.CharField(
        widget=HiddenInput(
            attrs={
                'name': 'permissions',
                'id': 'permissions'}),
        required=True)

    links = forms.MultipleChoiceField(
        label=_("Link to"),
        required=False)


    class Meta:
        model = Document
        fields = ['title', 'doc_file', 'doc_url']
        widgets = {
            'name': HiddenInput(attrs={'cols': 80, 'rows': 20}),
        }

    def __init__(self, *args, **kwargs):
        super(DocumentCreateForm, self).__init__(*args, **kwargs)
        self.fields['links'].choices = self.generate_link_choices()

    def clean_permissions(self):
        """
        Ensures the JSON field is JSON.
        """
        permissions = self.cleaned_data['permissions']

        try:
            return json.loads(permissions)
        except ValueError:
            raise forms.ValidationError(_("Permissions must be valid JSON."))

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentCreateForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(
                _("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(
                doc_file.name)[1].lower()[
                1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file

documents/templates/documents/document_base.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

documents/templates/documents/document_list.html
{% extends "documents/document_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Explore Documents" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents documents-list explore{% endblock %}

{% block body %}
<div class="page-header">
  <a href="{% url "document_upload" %}" class="btn btn-primary pull-right">{% trans "Upload Documents" %}</a>
  <h2>{% trans "Explore Documents" %}</h2>
</div>
  {% with include_type_filter='true' %}
  {% with header='Document Type' %}
  {% with filter='doc_type__in' %}
  {% include "search/_search_content.html" %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% include "_bulk_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
{{ block.super }}
  {% if GEONODE_SECURITY_ENABLED %}
    {% include "_permissions_form_js.html" %}
  {% endif %}
  <script type="text/javascript">
      {% if HAYSTACK_SEARCH %}
          SEARCH_URL = '{% url 'api_get_search' api_name='api' resource_name='documents'%}'
      {% else %}
          SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='documents' %}';
      {% endif %}
    FILTER_TYPE = 'document';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

documents/templates/documents/document_metadata.html
{% extends "metadata_base.html" %}
{% load i18n %}
{% load bootstrap_tags %}
{% load base_tags %}
{% load guardian_tags %}
{% load floppyforms %}

{% block title %}{{ document.title }} — {{ block.super }}{% endblock %}

{% block body_class %}data{% endblock body_class %}

{% block body_outer %}

{{ block.super }}

<div class="container-fluid page-header" style="position: relative;">
  <h2 class="page-title">{% trans "Metadata" %}&nbsp;{% blocktrans with document.title as document_title %}for {{ document_title }}{% endblocktrans %}</h2>
      <div id="profileCompleteness" class="alert alert-info" style="position: absolute; right: 0; top: 0; padding: 4px;">
        <strong>Completeness</strong>
        <div style="padding: 2px;">
          <small class="completed text-success" style="display: none; "><i class="fa fa-check"></i>Metadata Schema mandatory fields completed</small>
          <small class="not-completed text-danger" style="display: none; "><i class="fa fa-remove"></i>Check Schema mandatory fields</small>
        </div>
        <div class="progress" style="margin-bottom:2px;">
        <div class="progress-bar progress-bar-striped" role="progress-bar" >
          70%
        </div>
        </div>
      </div>
  </h2>
</div>

    <form id="metadata_update" class="form-horizontal" action="{% url "document_metadata" document.id %}" method="POST">
      {% if document_form.errors or category_form.errors or author_form.errors or poc.errors %}
        <p class="bg-danger">{% blocktrans %}Error updating metadata.  Please check the following fields: {% endblocktrans %}</p>
        <ul class="bg-danger">
        {% if author_form.errors %}
          <li>{% trans "Metadata Author" %}</li>
          {{ author_form.errors }}
        {% endif %}
        {% if poc_form.errors %}
          <li>{% trans "Point of Contact" %}</li>
          {{ poc_form.errors }}
        {% endif %}
        {% for field in document_form %}
            {% if field.errors %}
                <li>{{ field.label }}</li>
            {% endif %}
        {% endfor %}

        {% if category_form.errors %}
            <li>{{ category_form.errors.as_ul }}</li>
        {% endif %}
        </ul>
      {% endif %}

      {% csrf_token %}
        <div id="mdeditor_form" class="col-md-12 form-controls">
          {% form document_form using "layouts/doc_panels.html" %}
          {# document_form|as_bootstrap #}
        </div>

          <div class="row">
            <div class="col-md-12 grid-spacer">
              <fieldset class="form-controls modal-forms modal hide fade" id="poc_form" >
                <h2>{% trans "Point of Contact" %}</h2>
                {{ poc_form|as_bootstrap }}
                <button type='button' class="modal-cloose-btn btn btn-primary">Done</button>
              </fieldset>
              <fieldset class="form-controls modal-forms modal hide fade" id="metadata_form">
                <h2>{% trans "Metadata Provider" %}</h2>
                  {{ author_form|as_bootstrap }}
                <button type='button' class="modal-cloose-btn btn btn-primary">Done</button>
              </fieldset>

                <div class="form-actions">
                  <input type="button" id="btn_back_dwn" class="btn btn-primary" style="display: none" value="{% trans "<< Back" %}"/>
                  <input type="submit" id="btn_upd_md_dwn" class="btn btn-primary" value="{% trans "Update" %}"/>
                  <input type="button" id="btn_next_dwn" class="btn btn-primary" value="{% trans "Next >>" %}"/>
                </div>
            </div>
        </div>
    </form>
  </div>
</div>
{% endblock body_outer %}

{% block extra_script %}
{{ block.super }}
<script type="text/javascript">
    $("#id_resource-links").select2({
        placeholder: "Select an option",
        allowClear: true
    });
</script>
<style>
  #s2id_id_resource-links {
    width: 600px;
    height: 100%;
  }
</style>
{% endblock extra_script %}

documents/templates/documents/document_metadata_detail.html
{% extends "metadata_detail.html" %}

documents/templates/documents/document_remove.html
{% extends "documents/document_base.html" %}
{% load i18n %}

{% block title %}{% trans "Deleting" %} {{ document.title }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="page-header">
  <h2 class="page-title">{% trans "Remove Document" %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
        {% blocktrans with document.title as document_title %}
          Are you sure you want to remove <a href="{{ document.get_absolute_url }}">{{ document_title }}</a>?
        {% endblocktrans %}
      </p>
    <form action="{% url "document_remove" document.id %}" method="POST">
      {% csrf_token %}
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ document.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

documents/templates/documents/document_thumb_upload.html
{% extends "documents/document_upload_base.html" %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} {% trans "Upload Document's Thumbnail" %} - {{ block.super }} {% endblock %}

{% block body_class %}data documents upload{% endblock body_class %}

{% block head %}
    {% include "geoext/ext_header.html" %}
    {% include "geoext/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body_outer %}
  <div class="page-header">
    <a href="{% url "document_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Documents" %}</a>
    <h2 class="page-title">{% trans "Upload Document's Thumbnail" %}</h2>
  </div>

  <div class="row">
    {% block body %}
    <div class="col-md-8">
        {% block additional_info %}{% endblock %}

        {% if errors %}
        <div id="errors" class="alert alert-danger">
          {% for error in errors %}
          <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}

        <div id="upload-status"></div>

        <section id="drop-zone">
          <h3><i class="fa fa-cloud-upload"></i><br />{% trans "Drop files here" %}</h3>
        </section>

        <p>{% trans " or select them one by one:" %}</p>

        <form id="file-uploader" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
            <!-- UI change to hide the list of previously uploaded files from the user -->
            <input type="file" id="file-input" style="display: none;" multiple>
            <input class="btn btn-default" type="button" value="Choose Files" onclick="document.getElementById('file-input').click();">
        </form>

        <section class="widget">
          <ul id="global-errors"></ul>
          <h4>{% trans "Files to be uploaded" %}</h4>
          <div id="file-queue"></div>
          <div class="checkbox" style="display:none;" id="style_upload_form_check">
              Is Upload Metadata XML Form <input type="checkbox" name="style_upload_form" id="id_style_upload_form" checked="true"/>
              <input type="text" name="layer_title" id="id_layer_title" value="{{ resource.alternate }}"/>
          </div>
        </section>

        <section>
          <a href="{% url "document_thumb_upload" resource.id %}" id="clear-button" class="btn btn-default">{% trans "Clear" %}</a>
          <a href="#" id="upload-button" class="btn btn-danger">{% trans "Upload files" %}</a>
        </section>
        </div>

        {% endblock %}

        {% block sidebar %}
            <div class="col-md-4">
              <h3>{% trans "Permissions"  %}</h3>
              <form id="permission_form">
                {% include "_permissions.html" %}
              </form>
            </div>
        {% endblock %}
    </div>
</div>
{% endblock body_outer %}

{% block extra_script %}
    {{ block.super }}
    <script data-main="{% static 'geonode/js/upload/main' %}"
      src="{% static 'lib/js/require.js' %}">
    </script>
    <script type="text/javascript">
    {% autoescape off %}
      csrf_token =  "{{ csrf_token }}",
      form_target = "{% url "document_thumb_upload" docid=resource.id %}",
      geogig_enabled = {{ GEOGIG_ENABLED|lower  }},
      time_enabled = false,
      mosaic_enabled = false,
      userLookup = "{% url "account_ajax_lookup" %}"
    {% endautoescape %}
    </script>
    {% if GEONODE_SECURITY_ENABLED %}
        {% include "_permissions_form_js.html" %}
    {% endif %}

    <script type="text/javascript">
        $('#id_doc_file').on('change', function(){
            if($('#id_title').val() == ''){
                $('#id_title').val($('#id_doc_file').val().replace("C:\\fakepath\\", ""));
            }
        });
        $("#id_links").select2({
            width: '100%'
        });
        $('#upload_form').submit(function(){
          $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
        });
    </script>
{% endblock extra_script %}

documents/templates/documents/document_upload.html
{% extends "documents/document_upload_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} {% trans "Upload Document" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% block head %}
    {% include "geoext/ext_header.html" %}
    {% include "geoext/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}

<div class="col-md-8">
  <form id="upload_form"  method="post" enctype="multipart/form-data" action="{% url "document_upload" %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    {{ form.as_p }}
    <button type="submit" id="upload-button" class="btn btn-danger">{% trans "Upload" %}</button>
  </form>
</div>

{% endblock %}

{% block sidebar %}

<div class="col-md-4">
  <h3>{% trans "Permissions"  %}</h3>
  <form id="permission_form">
    {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
{{ block.super }}
{% include "_permissions_form_js.html" %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val().replace("C:\\fakepath\\", ""));
        }
    });
    $("#id_links").select2({
        width: '100%'
    });
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
    });

    $('#upload-button').click(function(){
      $('#_resource_uploading').modal('toggle');
    });
</script>
{% endblock extra_script %}